### ISSUE TITLE
GUI is stuck at 0/1016

### ISSUE THREAD

**Issue by JustAMalcontent** [fookatchu/SL1toPhoton#8]
Is this still being worked on? If so, I am having a problem with the GUI getting stuck.
![Converter](https://user-images.githubusercontent.com/59183999/82212632-b2914480-98c7-11ea-9079-8690cd0e3dab.jpg)

**Comment by fookatchu** [comment]
What version are you using? And which prusaslicer version did you use? It could also help if you supply the .sl1 file, so that I can better reproduce this.

**Comment by fookatchu** [comment]
This is linked to issue #6. I simply forgot to make a new release and binary. Should work now again!
