### ISSUE TITLE
Can't Change Layer Height

### ISSUE THREAD

**Issue by JustAMalcontent** [fookatchu/SL1toPhoton#9]
Sorry to bother your again, but I am having problems with adjusting the layer height. it seems to be stuck at 0.000 mm and cannot be increased to any size. The buttons are not working and I can't type anything in the text box.
![Layer Height Problem](https://user-images.githubusercontent.com/59183999/86870201-cae23c00-c08c-11ea-8f41-e6480a87bf79.jpg)

**Comment by fookatchu** [comment]
The converter unfortunately can't change the layer height. I know it looks like it could, but this was just an easy way to code a simple user interface. Sorry!
